server:
    port: 8000
spring:
    application:
        name: cto-gateway
eureka:
    client:
        service-url:
            defaultZone: http://localhost:9000/eureka/
zuul:
    routes:
        user:
            path: /user/**
            serviceId: cto-service-client-user
            stripPrefix: false
        auth:
            path: /auth/**
            serviceId: cto-auth
            stripPrefix: false
    sensitive-headers:
logging:
    level:
        com:
            cto:
                cloud: debug
        org:
            springframework:
                web: info
    file: log/cto-gateway.log